name: CI

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 6 * * 6'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install Nim
        uses: jiro4989/setup-nim-action@23b5809a314afab9cacb55285d88ece6a35e38dc
      - name: Install dep
        run: nimble install -y opengl
      - name: Build examples
        run: echo examples/*.nim | xargs -n1 -t nim c

  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dep
        run: pip install pycparser
      - name: Download CSFML
        uses: actions/checkout@v3
        with:
          repository: SFML/CSFML
          ref: '2.5'
          path: generate/CSFML
      - name: Re-generate sources
        run: generate/generate.sh
      - name: Validate freshness of generated files
        run: git diff --exit-code
